version: '3'
services:
  exercise1:
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - mongodb
      - mongodb2
  messageapp:
    image: "cabify/backend-bootcamp-messageapp:latest"
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  mongodb2:
    image: mongo
    volumes:
      - ./data2/db:/data/db
    ports:
      - 27018:27017